name: kubernetes_runner
on: push

jobs:
  kubernetes_runner:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: testing actions
        run: ls -ltra
