- name: Setting up the control plane
  hosts: localhost
  become: false
  tasks:
    - name: Push the secrets to gcp secret manager
      shell: |
        gcloud secrets versions add secret --data-file=/Users/manabpokhrel7/.kube/config
      # Replace with your kubeconfig absolute path