- name: Installing Cilium envoy
  hosts: control
  become: true
  tasks:
    - name: Installing prometheus stack
      shell: |
        helm upgrade --install kube-prometheus-stack oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack -n kube-prometheus-stack --create-namespace
