- name: Temp tasks
  become: yes
  hosts: workers
  vars:
    worker_lb_vip: "{{ hostvars['workerlb']['ansible_host'] }}"
  tasks:
    - name: enable firewall ports
      shell: |
        for n in worker1 worker2 worker3; do
          ssh $n 'readlink -f /dev/disk/by-id/google-ceph-device'
        done
      register: the_message

    - name: show message
      debug:
        var: the_message.stdout


