- name: Temp tasks
  become: yes
  hosts: workers
  tasks:
    - name: temp task
      shell: |
        dnf install -y iptables-services
        systemctl enable iptables  
        iptables -t nat -C PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 30080 || \  
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 30080  
        iptables -t nat -C PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 31977 || \ 
        iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 31977
        service iptables save
        systemctl restart iptables