- name: Workload Identity Federation for Kubernetes
  become: no
  hosts: localhost
  tasks:
    - name: Connect to your Kubernetes cluster and use kubectl to determine your cluster's issuer URL
      shell: |
        kubectl get --raw /.well-known/openid-configuration | jq -r .issuer
      register: cluster_issuer

    - name: Download the cluster's JSON Web Key Set (JWKS)
      shell: |
        kubectl get --raw /openid/v1/jwks > cluster-jwks.json

    - name: Create the WIF pool id
      shell: |
        gcloud iam workload-identity-pools create secret-pool \
        --location="global" \
        --description="This is the secret pool WIF" \
        --display-name="secret_pool" || true

    - name: Debug Issuer URI value
      ansible.builtin.debug:
        msg: "The issuer URI is: '{{ cluster_issuer.stdout }}'"

    - name: Add the Kubernetes cluster as a workload identity pool provider and upload the cluster's JWKS
      shell: |
        gcloud iam workload-identity-pools providers create-oidc secret-provider10 \
            --location="global" \
            --workload-identity-pool="secret-pool" \
            --issuer-uri="{{ cluster_issuer.stdout }}" \
            --attribute-mapping="google.subject=assertion.sub,attribute.namespace=assertion['kubernetes.io']['namespace'],attribute.service_account_name=assertion['kubernetes.io']['serviceaccount']['name'],attribute.pod=assertion['kubernetes.io']['pod']['name']" \
            --jwk-json-path="cluster-jwks.json"

    - name: Create a Kubernetes ServiceAccount
      shell: |
        kubectl create namespace react || true
        kubectl create serviceaccount external-secrets --namespace react || true

    - name: Grant IAM access to the Kubernetes ServiceAccount for a Google Cloud resource
      shell: |
        gcloud projects add-iam-policy-binding project-d64d7939-1f1b-470f-901 \
          --role=roles/secretmanager.secretAccessor \
          --member="principal://iam.googleapis.com/projects/$(gcloud projects describe project-d64d7939-1f1b-470f-901 --format='value(projectNumber)')/locations/global/workloadIdentityPools/secret-pool/subject/system:serviceaccount:react:external-secrets"  \    
          --condition=None
          
#        Pod
# ↓
#Kubernetes ServiceAccount
# ↓
#JWT issued by Kubernetes
# ↓
#External Secrets sends JWT to Google STS
# ↓
#Google uses secret-provider2
# ↓
#Provider validates:
#  - issuer
#  - signature
#  - audience
#  - jwks
# ↓
#Extracts:
#  sub=system:serviceaccount:react:external-secrets
# ↓
#Looks for IAM permissions
# ↓
#Finds Secret Manager Accessor role
# ↓
#Issues temporary Google credentials
# ↓
#External Secrets accesses Secret Manager
