- name: Join on the worker node
  hosts: workers
  become: true
  vars:
    worker_lb_vip: "{{ hostvars['workerlb']['ansible_host'] }}"
  tasks:
    - name: Update the cache
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Copy the join script
      ansible.builtin.copy:
        src: join.sh
        dest: /tmp/join.sh
      become: false
       
    - name: Execute the join command
      ansible.builtin.shell: sh /tmp/join.sh
      become: true
      # Add this to prevent joining a cluster you're already in
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Create a Persistent Volume location for kubernetes stateful apps we also created a persistenvolume.yaml file to mount to this location
      shell: |
        mkdir -p /mnt/data/ 

    - name: Add LB to linux we need to add this since out linux worker vm dont have any public ip so when it recieves healthcheck packets from the loadbalancer linux says i dont have a public ip and drops the packets
      ansible.builtin.shell: |
          ip addr show lo | grep -q "{{ worker_lb_vip }}/32" || ip addr add "{{ worker_lb_vip }}/32" dev lo

    - name: Since we have nothing listening on port 80/443 from where the lb traffic comes from envoy is only listening on nodeports we need to do port mapping else linux drops the packet as well
      shell: |
        dnf install -y iptables-services
        systemctl enable iptables  
        iptables -t nat -C PREROUTING -d "{{ worker_lb_vip }}/32" -p tcp --dport 80 -j REDIRECT --to-port 30080 || \
        iptables -t nat -A PREROUTING -d "{{ worker_lb_vip }}/32" -p tcp --dport 80 -j REDIRECT --to-port 30080
        iptables -t nat -C PREROUTING -d "{{ worker_lb_vip }}/32" -p tcp --dport 443 -j REDIRECT --to-port 31977 || \
        iptables -t nat -A PREROUTING -d "{{ worker_lb_vip }}/32" -p tcp --dport 443 -j REDIRECT --to-port 31977
        service iptables save
        systemctl restart iptables