- name: Join on the worker node
  hosts: workers
  become: true
  gather_facts: true
  vars:
    worker_lb_vip: "{{ hostvars['workerlb']['ansible_host'] }}"
  tasks:
    - name: Update the cache
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Copy the join script
      ansible.builtin.copy:
        src: join.sh
        dest: /tmp/join.sh
      become: false
       
    - name: Execute the join command
      ansible.builtin.shell: sh /tmp/join.sh
      become: true
      # Add this to prevent joining a cluster you're already in
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Create a Persistent Volume location for kubernetes stateful apps we also created a persistenvolume.yaml file to mount to this location
      shell: |
        mkdir -p /mnt/data/ 

    - name: Add LB to linux we need to add this since out linux worker vm dont have any public ip so when it recieves healthcheck packets from the loadbalancer linux says i dont have a public ip and drops the packets
      ansible.builtin.shell: |
          ip addr show lo | grep -q "{{ worker_lb_vip }}/32" || ip addr add "{{ worker_lb_vip }}/32" dev lo

    - name: Install Ip tables
      dnf:
        name: iptables-services
        state: present

    - name: Enable a iptables-services
      ansible.builtin.systemd_service:
        name: iptables-services
        state: started

    - name: Configure LB NAT rules
      shell: |
        WORKER_IP=$(ip -4 addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1)
        iptables -t nat -D CILIUM_PRE_nat -d {{ worker_lb_vip }}/32 -p tcp --dport 80 -j DNAT --to-destination ${WORKER_IP}:30080 2>/dev/null || true
        iptables -t nat -D CILIUM_PRE_nat -d {{ worker_lb_vip }}/32 -p tcp --dport 443 -j DNAT --to-destination ${WORKER_IP}:31974 2>/dev/null || true
        iptables -t nat -I CILIUM_PRE_nat 1 -d {{ worker_lb_vip }}/32 -p tcp --dport 80 -j DNAT --to-destination ${WORKER_IP}:30080
        iptables -t nat -I CILIUM_PRE_nat 2 -d {{ worker_lb_vip }}/32 -p tcp --dport 443 -j DNAT --to-destination ${WORKER_IP}:31974
        iptables -t nat -D CILIUM_POST_nat -p tcp -d ${WORKER_IP}/32 --dport 30080 -j MASQUERADE 2>/dev/null || true
        iptables -t nat -D CILIUM_POST_nat -p tcp -d ${WORKER_IP}/32 --dport 31974 -j MASQUERADE 2>/dev/null || true
        iptables -t nat -I CILIUM_POST_nat 1 -p tcp -d ${WORKER_IP}/32 --dport 30080 -j MASQUERADE
        iptables -t nat -I CILIUM_POST_nat 2 -p tcp -d ${WORKER_IP}/32 --dport 31974 -j MASQUERADE
      args:
        executable: /bin/bash
      # Nothing is listening on port 80 and 443 so we route them to 30080
      # and 31974 where envoy ports are configured and we added our LB public ip to out linux
      # system but the envoy isnt listening in the LB public ip it is listening on its internal
      # ip so we are mapping out our LB public ip to linux internal ip since thats where envoy is listening on
