apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://charts.rook.io/release'
    chart: rook-ceph-cluster
    targetRevision: v1.20.1
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true

