apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 0.19.1
    chart: eck-stack
    helm:
      values: |
        eck-operator:
          enabled: true
        
        eck-kibana:
          enabled: true
        
        eck-fleet-server:
          enabled: true
        
        eck-agent:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
