apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/manabpokhrel7/Kubeadm-cilium-Terraform.git'
    targetRevision: main
    path: manifests/kube-prometheus-stack
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/kube-stack-config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
