apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/manabpokhrel7/Kubeadm-cilium-Terraform.git'
    targetRevision: main
    path: manifests/redis
    helm:
      valueFiles:
        - values.yaml
#        - env/dev/dev-values.yaml     # optional layered override
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
