apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/manabpokhrel7/Kubeadm-cilium-Terraform.git'
    targetRevision: main
    path: manifests/cert-manager
#    helm:
#      valueFiles:
#        - values.yaml
#        - env/dev/dev-values.yaml     # optional layered override
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
