apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  mgr:
    count: 1
  resources:
    mon:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        memory: "1Gi"
    mgr:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        memory: "1Gi"
    osd:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        memory: "2Gi"
    prepareosd:
      requests:
        cpu: "100m"
        memory: "256Mi"
    crashcollector:
      requests:
        cpu: "25m"
        memory: "64Mi"
    exporter:
      requests:
        cpu: "25m"
        memory: "64Mi"
  dataDirHostPath: /var/lib/rook # Mon data will live here on the VM OS drive
  mon:
    count: 3
    allowMultiplePerNode: false
    # Removed volumeClaimTemplate from here because we aren't using a StorageClass
  cephVersion:
    image: quay.io/ceph/ceph:v20.2.2
    allowUnsupported: false
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      # You can put resource placement/limits for your OSDs inside this general block if needed
    nodes:
      - name: "worker1"
        devices:
          - name: "sdb"
            metadataDevice: "worker1"
      - name: "worker2"
        devices:
          - name: "sdb"
            metadataDevice: "worker2"
      - name: "worker3"
        devices:
          - name: "sdb"
            metadataDevice: "worker3"
