#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgres-config
#  namespace: {{ .Values.namespace }}
#data:
#  POSTGRES_USER: {{ .Values.postgres.user | quote }}
#  POSTGRES_DB: {{ .Values.postgres.database | quote }}