apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: python
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: python-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: python-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: python-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: python-config
                  key: DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: python-config
                  key: REDIS_HOST
          startupProbe:
            httpGet:
              path: /health # Requires a health endpoint in your FastAPI app
              port: 8000
            failureThreshold: 6
            periodSeconds: 5 # Gives the app up to 30 seconds to connect to DB and start
            # 2. Liveness Probe: Restarts the pod if the app deadlocks or crashes
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
            # 3. Readiness Probe: Cuts off traffic if the DB connection drops temporarily
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2