apiVersion: v1
kind: Secret
metadata:
  name: python-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASS: {{ .Values.secret.DB_PASS | b64enc | quote }}
#  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY }}