apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: react
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}