apiVersion: v1
kind: Namespace
metadata:
  name: react
  labels:
    name: react
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
