apiVersion: v1
kind: ConfigMap
metadata:
  name: python-config
  namespace: react
data:
  DB_HOST: postgres-service.database.svc.cluster.local
  DB_USER: "postgres"
  DB_NAME: "amldb"
  REDIS_HOST: redis-service.redis.svc.cluster.local
