namespace: react
replicaCount: 3
image:
  repository: manabpokhrel7/python-cloud
  tag: 7cb05edb49feb85b38cf695fc395b1ab7b107618
  pullPolicy: Always
config:
  DB_HOST: postgres-service.database.svc.cluster.local
  DB_USER: postgres
  DB_NAME: amldb
  REDIS_HOST: redis-service.redis.svc.cluster.local
secret:
  DB_PASS: Sujankhadka77$
service:
  name: python-service
  type: ClusterIP
  port: 8000
  targetPort: 8000
