namespace: react
replicaCount: 3
image:
  repository: manabpokhrel7/python-cloud
  tag: 2fadd628c5f85dbc5d22cf0c31b6f9f73240dd88
  pullPolicy: Always
config:
  DB_HOST: postgres-rw.database.svc.cluster.local
  DB_USER: manab
  DB_NAME: amldb
  REDIS_HOST: redis-service.redis.svc.cluster.local
secret:
  DB_PASS: Sujankhadka77$
service:
  name: python-service
  type: ClusterIP
  port: 8000
  targetPort: 8000
