namespace: react
replicaCount: 3
image:
  repository: manabpokhrel7/python-cloud
  tag: 3d6cfec44b558acf3e8fcf8247019e8d877e8ccf
  pullPolicy: Always
config:
  DB_HOST: postgres-rw.database.svc.cluster.local
  DB_USER: manab
  DB_NAME: amldb
  REDIS_HOST: redis-service.redis.svc.cluster.local
secret:
  DB_PASS: Sujankhadka77$
service:
  name: python-service
  type: ClusterIP
  port: 8000
  targetPort: 8000
