apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openapi-external-secret
  namespace: react
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: openapi-secrets #Secret name that kubernetes will create by ESO
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY #Secret key that will be created by ESO in kube
    remoteRef:
      key: openai-secret #GCP secret manager key
  - secretKey: GOOGLE_CLIENT_ID
    remoteRef:
      key: google-client-id
  - secretKey: GOOGLE_CLIENT_SECRET
    remoteRef:
      key: google-client-secret
  - secretKey: TOKEN_URI
    remoteRef:
      key: token-uri
  - secretKey: SECRET_KEY
    remoteRef:
      key: secret-key