apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: react
spec:
  provider:
    gcpsm:
      projectID: kubeadm-public-ip-lab
      auth:
        workloadIdentity:
          clusterLocation: us-west1
          serviceAccountRef:
            name: external-secrets