apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: react
spec:
  provider:
    gcpsm:
      projectID: project-d64d7939-1f1b-470f-901
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/728899142899/locations/global/workloadIdentityPools/secret-pool/providers/secret-provider9
          serviceAccountRef:
            name: external-secrets
            namespace: react
            audiences:
              - https://iam.googleapis.com/projects/728899142899/locations/global/workloadIdentityPools/secret-pool/providers/secret-provider9