apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: react
spec:
  provider:
    gcpsm:
      projectID: kubeadm-public-ip-lab
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/656057285850/locations/global/workloadIdentityPools/secret-pool/providers/secret-provider31
          serviceAccountRef:
            name: external-secrets
            namespace: react
            audiences:
              - https://iam.googleapis.com/projects/656057285850/locations/global/workloadIdentityPools/secret-pool/providers/secret-provider31