apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: react
  labels:
    app.kubernetes.io/name: "python-service"
spec:
  selector:
    app: python
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
