namespace: react
replicaCount: 3
image:
  repository: manabpokhrel7/reactjs
  tag: b218daf280c094abbd2ad5cef1855c9a1ccc123a
  pullPolicy: Always
service:
  name: react-service
  type: ClusterIP
  port: 80
  targetPort: 80
