namespace: react
replicaCount: 3
image:
  repository: manabpokhrel7/reactjs
  tag: c4e5f629bd3480f7b19f923d3bad785065bf06b9
  pullPolicy: Always
service:
  name: react-service
  type: ClusterIP
  port: 80
  targetPort: 80
