namespace: react
replicaCount: 3
image:
  repository: manabpokhrel7/reactjs
  tag: e82087917f910337463b56978f4dff8337dea3a3
  pullPolicy: Always
service:
  name: react-service
  type: ClusterIP
  port: 80
  targetPort: 80
