namespace: database

postgres:
  image: postgres:15
  user: postgres
  database: amldb
  password: Sujankhadka77$

service:
  name: postgres-service
  port: 5432

storage:
  className: ceph-block
  size: 5Gi

replicaCount: 1