apiVersion: v1
kind: Namespace
metadata:
  name: react
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd