# Nginx is required to listen on 80 and 443 where our lb is forwarding and it is forwarding to envoy nodeport where envoy is listening
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-edge-config
  namespace: envoy-gateway-system
data:
  nginx.conf: |
    events {}

    stream {
      server {
        listen 443;
        proxy_pass 127.0.0.1:31974;
      }
    }

    http {
      server {
        listen 80;

        location / {
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:30080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto http;
          proxy_set_header Connection "";
        }
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-edge-proxy
  namespace: envoy-gateway-system
spec:
  selector:
    matchLabels:
      app: nginx-edge-proxy
  template:
    metadata:
      labels:
        app: nginx-edge-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-edge-config