apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.storage.path | quote }}